/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

/**
 *
 * @author deivid
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textOperacion = new javax.swing.JLabel();
        textoResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 251));

        textOperacion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        textOperacion.setForeground(new java.awt.Color(102, 102, 102));
        textOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textOperacion.setText("5 x 10 +20");

        textoResultado.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        textoResultado.setForeground(new java.awt.Color(51, 51, 51));
        textoResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoResultado.setText("1244554");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(textOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoResultado)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton9.setText("%");
        jButton9.setBorder(null);
        jButton9.setFocusPainted(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, 50));

        jButton13.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("=");
        jButton13.setBorder(null);
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, 50));

        jButton14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton14.setText("9");
        jButton14.setBorder(null);
        jButton14.setFocusPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, 50));

        jButton15.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton15.setText("^");
        jButton15.setBorder(null);
        jButton15.setFocusPainted(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 50));

        jButton16.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton16.setText("/");
        jButton16.setBorder(null);
        jButton16.setFocusPainted(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, 50));

        jButton17.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton17.setText("x");
        jButton17.setBorder(null);
        jButton17.setFocusPainted(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, 50));

        jButton18.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton18.setText("-");
        jButton18.setBorder(null);
        jButton18.setFocusPainted(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, 60));

        jButton19.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton19.setText("+");
        jButton19.setBorder(null);
        jButton19.setFocusPainted(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, 50));

        jButton20.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton20.setText("C");
        jButton20.setBorder(null);
        jButton20.setFocusPainted(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        jButton21.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton21.setText("7");
        jButton21.setBorder(null);
        jButton21.setFocusPainted(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 50));

        jButton26.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton26.setText("4");
        jButton26.setBorder(null);
        jButton26.setFocusPainted(false);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 50));

        jButton27.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton27.setText("5");
        jButton27.setBorder(null);
        jButton27.setFocusPainted(false);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 50));

        jButton28.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton28.setText("6");
        jButton28.setBorder(null);
        jButton28.setFocusPainted(false);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 50));

        jButton29.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton29.setText("1");
        jButton29.setBorder(null);
        jButton29.setFocusPainted(false);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 50));

        jButton30.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton30.setText("2");
        jButton30.setBorder(null);
        jButton30.setFocusPainted(false);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 60, 50));

        jButton31.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton31.setText("3");
        jButton31.setBorder(null);
        jButton31.setFocusPainted(false);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 60, 50));

        jButton33.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton33.setText("8");
        jButton33.setBorder(null);
        jButton33.setFocusPainted(false);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 50));

        jButton35.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton35.setText("0");
        jButton35.setBorder(null);
        jButton35.setFocusPainted(false);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 50));

        jButton36.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jButton36.setText(".");
        jButton36.setBorder(null);
        jButton36.setFocusPainted(false);
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 310, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textOperacion;
    private javax.swing.JLabel textoResultado;
    // End of variables declaration//GEN-END:variables
}
